import java.io.IOException;

public class Exceptionagain {
	public static void main(String[] args) {
		
	
	try {
		
		System.out.println("hi");
		
	}
	//not allowed as it will never reach in case of checked exception
	catch(IOException e) {
		
		
		
	}
	
	
	
	

}
}